import { HardHat, Factory, TrendingUp, Scale } from 'lucide-react'
import type { Sector } from '@/types/sector'

export const SECTORS: Sector[] = [
  {
    id: 'industrie',
    name: 'Industrie',
    description:
      'Maintenance predictive, fiches techniques, procedures qualite et certifications ISO.',
    icon: Factory,
    color: '#30D982',
    colorVar: 'var(--gn)',
    gradient: 'from-green-500/20 to-green-600/5',
    painPoint: '2 heures perdues par jour',
    painPointSub: 'soit 15 000 € par an et par technicien en coût caché',
    roiPrimary: '-30% pannes',
    roiSecondary: 'Zéro retard certification',
    roiThird: 'MTTR réduit de moitié',
    metrics: [
      { label: 'Fiches techniques', value: '1,800+' },
      { label: 'Precision', value: '89%' },
      { label: 'Sources citees', value: '100%' },
    ],
    useCases: [
      {
        question: 'Quelle est la procedure de maintenance preventive pour un compresseur Atlas Copco GA30+ ?',
        label: 'Maintenance',
        roi: '-40% arrets non planifies',
        description: 'Accès instantané aux procédures de maintenance préventive et corrective pour tous vos équipements industriels.',
        problem: 'Les techniciens perdent 45 min par intervention à chercher la bonne procédure dans les manuels papier.',
        timeSaved: '45 min/intervention',
        moneySaved: '85K€/an',
      },
      {
        question: 'Quelles sont les exigences ISO 9001:2015 pour la maitrise des documents ?',
        label: 'ISO 9001',
        roi: 'Audit-ready',
        description: 'Navigation instantanée dans les référentiels ISO et les procédures qualité de votre entreprise.',
        problem: 'Préparation des audits de certification chronophage — 3 semaines de mobilisation équipe qualité.',
        timeSaved: '2 semaines/audit',
        moneySaved: '45K€/an',
      },
      {
        question: 'Comment calibrer un capteur de pression differentielle ?',
        label: 'Calibration',
        roi: '-60% temps calibration',
        description: 'Guides de calibration étape par étape avec tolérances et fréquences réglementaires.',
        problem: 'Erreurs de calibration fréquentes par manque d\'accès aux spécifications constructeur à jour.',
        timeSaved: '30 min/calibration',
        moneySaved: '60K€/an',
      },
      {
        question: 'Quelles sont les obligations de l\'exploitant pour un site classe Seveso seuil haut ?',
        label: 'Seveso/ICPE',
        roi: 'Zero non-conformite',
        description: 'Synthèse réglementaire Seveso/ICPE personnalisée à votre classification et vos installations.',
        problem: 'Veille réglementaire ICPE dispersée entre DREAL, préfecture et textes européens.',
        timeSaved: '8h/semaine',
        moneySaved: '120K€/an',
      },
      {
        question: 'Comment realiser une analyse AMDEC sur une ligne de production automobile ?',
        label: 'AMDEC/FMEA',
        roi: '2.5M EUR/an ROI',
        description: 'Assistance à la réalisation d\'analyses AMDEC avec cotation automatique et plans d\'action.',
        problem: 'Analyses AMDEC incomplètes par manque de données historiques sur les modes de défaillance.',
        timeSaved: '3 jours/analyse',
        moneySaved: '200K€/an',
      },
      {
        question: 'Comment optimiser la gestion des pieces de rechange pour reduire les couts de stock de 25% ?',
        label: 'Supply Chain',
        roi: '-25% couts stock',
        description: 'Optimisation des niveaux de stock pièces de rechange par analyse prédictive des consommations.',
        problem: 'Sur-stockage de pièces rarement utilisées et ruptures sur les pièces critiques.',
        timeSaved: '10h/semaine',
        moneySaved: '180K€/an',
      },
    ],
    videoScript: [
      { time: '0-5s', voice: '« Vos équipes perdent 2 heures par jour à chercher des informations techniques ? »', screen: '2h/jour perdues → Coût caché : 15 000€/an par technicien' },
      { time: '5-11s', voice: '« Notre IA donne la réponse instantanément. Manuels, procédures ATEX, fiches sécurité : tout est accessible en un instant. »', screen: 'Réponse immédiate vs 2 heures de recherche' },
      { time: '11-17s', voice: '« Maintenance préventive : vos techniciens ont les bonnes procédures, immédiatement. Résultat : 30% moins de pannes imprévues. »', screen: '−30% de pannes / MTTR réduit de moitié' },
      { time: '17-23s', voice: '« Qualité et conformité : une non-conformité ? Le chatbot trace la procédure corrective en temps réel. Zéro retard de certification. »', screen: 'Zéro retard audit / 100% traçable' },
      { time: '23-28s', voice: '« Déployé en 48h. ROI mesurable dès le premier mois. Demandez votre démo gratuite. »', screen: 'ROI 1er mois / Démo gratuite' },
    ],
  },
  {
    id: 'btp',
    name: 'BTP & Construction',
    description:
      'Normes DTU, reglementations, CCTP et specifications techniques du batiment.',
    icon: HardHat,
    color: '#4C8BF5',
    colorVar: 'var(--ac)',
    gradient: 'from-blue-500/20 to-blue-600/5',
    painPoint: '3 heures perdues par jour',
    painPointSub: 'à chercher des informations techniques sur vos chantiers',
    roiPrimary: '+20% productivité',
    roiSecondary: 'Zéro oubli de norme',
    roiThird: 'Devis plus justes',
    metrics: [
      { label: 'Documents indexes', value: '2,400+' },
      { label: 'Precision', value: '92%' },
      { label: 'Sources citees', value: '100%' },
    ],
    useCases: [
      {
        question: 'Quelles sont les normes DTU pour l\'isolation thermique des murs exterieurs ?',
        label: 'Normes DTU',
        roi: '-70% temps recherche',
        description: 'Recherche instantanée dans l\'intégralité des DTU, Eurocodes et normes NF applicables.',
        problem: 'Les conducteurs de travaux passent 2h/jour à naviguer entre DTU papier et sites officiels.',
        timeSaved: '2h/jour',
        moneySaved: '95K€/an',
      },
      {
        question: 'Quels sont les seuils reglementaires RE2020 pour un batiment tertiaire ?',
        label: 'RE2020',
        roi: 'Conformite garantie',
        description: 'Calculs et seuils RE2020 personnalisés selon zone climatique, type de bâtiment et surface.',
        problem: 'Erreurs de conformité RE2020 découvertes tardivement — reprises coûteuses en phase chantier.',
        timeSaved: '5h/projet',
        moneySaved: '75K€/an',
      },
      {
        question: 'Comment rediger un CCTP pour un lot plomberie ?',
        label: 'CCTP',
        roi: '-50% redaction',
        description: 'Génération assistée de CCTP conformes avec clauses techniques adaptées à chaque lot.',
        problem: 'Rédaction de CCTP chronophage et risque d\'oubli de clauses techniques obligatoires.',
        timeSaved: '4h/CCTP',
        moneySaved: '55K€/an',
      },
      {
        question: 'Quelles verifications CSPS sont obligatoires avant la reception d\'un chantier de demolition ?',
        label: 'Securite chantier',
        roi: '-35% risques accidents',
        description: 'Check-lists sécurité CSPS complètes et adaptées au type de chantier et aux risques identifiés.',
        problem: 'Vérifications sécurité incomplètes par méconnaissance des obligations CSPS spécifiques.',
        timeSaved: '3h/reception',
        moneySaved: '110K€/an',
      },
      {
        question: 'Comment calculer le Bbio max d\'un projet de logement collectif en zone H2b ?',
        label: 'Calcul thermique',
        roi: '2.4M EUR/an ROI',
        description: 'Assistance aux calculs thermiques réglementaires avec les coefficients de votre zone.',
        problem: 'Calculs thermiques externalisés systématiquement — délais et coûts de bureaux d\'études.',
        timeSaved: '2 jours/projet',
        moneySaved: '130K€/an',
      },
      {
        question: 'Comment generer automatiquement un PPSPS conforme pour un chantier de demolition ?',
        label: 'Plan de prevention',
        roi: '-80% temps redaction',
        description: 'Génération automatique de PPSPS conformes à partir du type de chantier et des risques identifiés.',
        problem: 'Rédaction manuelle de PPSPS — 2 jours par document, souvent non conformes à l\'inspection.',
        timeSaved: '1.5 jours/PPSPS',
        moneySaved: '90K€/an',
      },
    ],
    videoScript: [
      { time: '0-5s', voice: '« Vos équipes perdent 3 heures par jour à chercher des informations ? »', screen: '[3H/JOUR PERDUES] Recherche d\'infos technique' },
      { time: '5-12s', voice: '« Notre IA RAG trouve l\'info exacte dans vos documents. Un DTU, un CCAP, un plan de chantier : elle trouve l\'info exacte dans vos milliers de documents. »', screen: '[RÉPONSE EXPERTE SOURCÉE] DTU • CCAP • Plans • Vos documents internes' },
      { time: '12-19s', voice: '« Résultat : moins d\'erreurs de devis, zéro oubli de norme, et vos chantiers livrés dans les délais. »', screen: '[ROI CONCRET] Devis plus justes / Conformité garantie / Délais tenus' },
      { time: '19-25s', voice: '« Les ETI du BTP gagnent 20% de productivité. Vos équipes se concentrent sur l\'exécution, pas la paperasse. »', screen: '[+20% PRODUCTIVITÉ] BTP & Construction' },
      { time: '25-30s', voice: '« Démo personnalisée sur vos propres documents. Réservez votre créneau. »', screen: '[DÉMO GRATUITE] 30 min, vos docs, vos cas d\'usage' },
    ],
  },
  {
    id: 'finance',
    name: 'Finance',
    description:
      'Analyse financiere, reglementations bancaires, ratios et reporting IFRS.',
    icon: TrendingUp,
    color: '#F5B731',
    colorVar: 'var(--yl)',
    gradient: 'from-yellow-500/20 to-yellow-600/5',
    painPoint: '40% du temps en veille réglementaire',
    painPointSub: 'AMF, BCE, Bâle III — une lecture manuelle chronophage et risquée',
    roiPrimary: '+12h/semaine',
    roiSecondary: '-60% risque réglementaire',
    roiThird: 'KYC 4x plus vite',
    metrics: [
      { label: 'Rapports indexes', value: '3,200+' },
      { label: 'Precision', value: '94%' },
      { label: 'Sources citees', value: '100%' },
    ],
    useCases: [
      {
        question: 'Quels sont les ratios prudentiels Bale III pour une banque de detail ?',
        label: 'Bale III',
        roi: 'Conformite regulatoire',
        description: 'Navigation instantanée dans Bâle III/IV avec calculs de ratios prudentiels automatisés.',
        problem: 'Interprétation des textes Bâle III complexe — risque d\'erreur de calcul des ratios CET1/LCR.',
        timeSaved: '6h/semaine',
        moneySaved: '150K€/an',
      },
      {
        question: 'Comment calculer le ratio de liquidite LCR selon les normes europeennes ?',
        label: 'LCR',
        roi: '-80% temps calcul',
        description: 'Calcul assisté du LCR avec classification automatique des actifs liquides de haute qualité.',
        problem: 'Calculs LCR manuels sur tableurs — erreurs fréquentes et reporting BCE en retard.',
        timeSaved: '4h/rapport',
        moneySaved: '90K€/an',
      },
      {
        question: 'Quelles sont les nouvelles regles IFRS 17 pour les contrats d\'assurance ?',
        label: 'IFRS 17',
        roi: 'Mise en conformite',
        description: 'Synthèse IFRS 17 avec impact sur vos contrats existants et plan de transition.',
        problem: 'Transition IFRS 17 retardée par manque de compréhension des nouvelles exigences.',
        timeSaved: '10h/semaine',
        moneySaved: '200K€/an',
      },
      {
        question: 'Quel est l\'impact d\'une hausse de 50bps du taux directeur sur notre portefeuille obligataire ?',
        label: 'Stress test',
        roi: '3.5M EUR/an ROI',
        description: 'Simulation de stress tests réglementaires avec analyse d\'impact sur vos portefeuilles.',
        problem: 'Stress tests EBA réalisés tardivement — résultats soumis sous pression avec risque d\'erreur.',
        timeSaved: '2 jours/test',
        moneySaved: '250K€/an',
      },
      {
        question: 'Quelles sont les exigences KYC renforcees pour les PPE dans le cadre de la 6e directive AML ?',
        label: 'KYC/AML',
        roi: '-90% risque sanction',
        description: 'Vérification KYC automatisée avec screening PPE et analyse de risque AML en temps réel.',
        problem: 'Processus KYC manuels — 45 min par client, backlog de dossiers en attente.',
        timeSaved: '35 min/dossier',
        moneySaved: '180K€/an',
      },
      {
        question: 'Comment detecter les anomalies de transactions pour reduire les faux positifs AML de 75% ?',
        label: 'AML Detection',
        roi: '-75% faux positifs',
        description: 'Détection intelligente des anomalies transactionnelles avec réduction massive des faux positifs.',
        problem: '95% des alertes AML sont des faux positifs — équipes compliance submergées et démotivées.',
        timeSaved: '15h/semaine',
        moneySaved: '320K€/an',
      },
    ],
    videoScript: [
      { time: '0-5s', voice: '« Vos équipes passent encore des heures à fouiller vos réglementations ? »', screen: '[Votre temps, c\'est de l\'argent.]' },
      { time: '5-12s', voice: '« Notre IA RAG répond instantanément sur AMF, BCE, Bâle III. KYC validé 4 fois plus vite. Zéro erreur de conformité. »', screen: '[AMF • BCE • Bâle III] / [KYC : -75% de temps] / [Conformité : 0 erreur]' },
      { time: '12-19s', voice: '« Contrats clients, rapports d\'audit, analyses financières : tout devient accessible, instantanément. »', screen: '[100% de vos documents] / [1 question = 1 réponse]' },
      { time: '19-26s', voice: '« Résultat ? Vos équipes gagnent 12 heures par semaine. Vous réduisez vos risques réglementaires de 60%. »', screen: '[+12h/semaine gagnées] / [-60% de risque]' },
      { time: '26-30s', voice: '« Démonstration personnalisée. Cette semaine. »', screen: '[Réservez votre démo →]' },
    ],
  },
  {
    id: 'juridique',
    name: 'Juridique',
    description:
      'Code civil, jurisprudence, contrats types et veille reglementaire.',
    icon: Scale,
    color: '#F08838',
    colorVar: 'var(--or)',
    gradient: 'from-orange-500/20 to-orange-600/5',
    painPoint: '40% du temps en recherche',
    painPointSub: 'jurisprudence, codes, doctrine — introuvable en moins d\'une heure',
    roiPrimary: '-15h par dossier',
    roiSecondary: '+35% productivité',
    roiThird: 'Zéro sanction',
    metrics: [
      { label: 'Articles de loi', value: '5,000+' },
      { label: 'Precision', value: '91%' },
      { label: 'Sources citees', value: '100%' },
    ],
    useCases: [
      {
        question: 'Quelles sont les obligations de l\'employeur en matiere de teletravail selon le Code du travail ?',
        label: 'Teletravail',
        roi: '-60% recherche juridique',
        description: 'Recherche instantanée dans le Code du travail avec jurisprudence applicable et doctrine.',
        problem: 'Recherche jurisprudentielle dispersée entre Légifrance, Dalloz et bases internes.',
        timeSaved: '3h/recherche',
        moneySaved: '95K€/an',
      },
      {
        question: 'Quels sont les delais de prescription en matiere contractuelle ?',
        label: 'Prescription',
        roi: 'Securite juridique',
        description: 'Calcul automatique des délais de prescription avec exceptions et interruptions applicables.',
        problem: 'Erreurs sur les délais de prescription — risque de forclusion et responsabilité professionnelle.',
        timeSaved: '1h/dossier',
        moneySaved: '75K€/an',
      },
      {
        question: 'Comment rediger une clause de non-concurrence conforme a la jurisprudence ?',
        label: 'Non-concurrence',
        roi: '-50% revision contrats',
        description: 'Génération de clauses contractuelles conformes à la jurisprudence récente de la Cour de cassation.',
        problem: 'Clauses de non-concurrence invalidées par les tribunaux — contentieux et indemnités.',
        timeSaved: '2h/contrat',
        moneySaved: '110K€/an',
      },
      {
        question: 'Quelles clauses du contrat de sous-traitance presentent un risque de requalification en salariat deguise ?',
        label: 'Analyse contrats',
        roi: '3.2M EUR/an ROI',
        description: 'Analyse automatique de contrats avec identification des clauses à risque juridique.',
        problem: 'Contrats de sous-traitance non revus — risque de requalification URSSAF avec redressement.',
        timeSaved: '4h/contrat',
        moneySaved: '250K€/an',
      },
      {
        question: 'Quel est l\'etat actuel de la jurisprudence sur le devoir de vigilance des societes meres (loi Sapin II) ?',
        label: 'Compliance',
        roi: 'Zero risque penal',
        description: 'Veille jurisprudentielle automatisée sur le devoir de vigilance et la compliance anticorruption.',
        problem: 'Veille compliance manuelle — 2 jours/semaine pour suivre l\'évolution réglementaire.',
        timeSaved: '1.5 jours/semaine',
        moneySaved: '130K€/an',
      },
      {
        question: 'Comment identifier automatiquement les clauses abusives dans un bail commercial ?',
        label: 'Analyse baux',
        roi: '-70% temps analyse',
        description: 'Analyse automatique de baux commerciaux avec identification des clauses abusives ou déséquilibrées.',
        problem: 'Analyse de baux commerciaux fastidieuse — 4h par bail, risque de clauses léonines non détectées.',
        timeSaved: '3h/bail',
        moneySaved: '85K€/an',
      },
    ],
    videoScript: [
      { time: '0-5s', voice: '« Vos juristes passent 40% de leur temps à chercher des informations. »', screen: '40% du temps perdu en recherche' },
      { time: '5-10s', voice: '« Interrogez la jurisprudence instantanément. 15 heures de recherche économisées par dossier. »', screen: 'Jurisprudence instantanée | -15h par dossier' },
      { time: '10-15s', voice: '« Veille réglementaire RGPD et droit des sociétés en temps réel. Zéro sanction évitée. »', screen: 'Conformité temps réel | Zéro risque' },
      { time: '15-20s', voice: '« Contrats types et clauses générés instantanément. ROI : +35% de productivité juridique. »', screen: 'Contrats instantanés | +35% productivité' },
      { time: '20-30s', voice: '« Déjà 80 cabinets et directions juridiques nous font confiance. Démo personnalisée sous 48h. »', screen: '80+ cabinets équipés / Démonstration sous 48h' },
    ],
  },
]
