#!/bin/bash
# inventory-update.sh — Automated file counting across all 5 repos
# Updates infra/inventory.md with precise counts
# Usage: bash scripts/inventory-update.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INVENTORY="$REPO_ROOT/infra/inventory.md"
NOW=$(TZ="Europe/Paris" date +"%Y-%m-%dT%H:%M:%S%:z")

echo "=== Inventory Update — $NOW ==="

# Count files in local repo (excluding .git, node_modules, .next, __pycache__, .venv)
count_local() {
    local dir="$1"
    if [ -d "$dir" ]; then
        find "$dir" -type f \
            -not -path '*/.git/*' \
            -not -path '*/node_modules/*' \
            -not -path '*/.next/*' \
            -not -path '*/__pycache__/*' \
            -not -path '*/.venv/*' \
            -not -path '*/.mypy_cache/*' \
            -not -path '*/.pytest_cache/*' \
            | wc -l | tr -d ' '
    else
        echo "N/A"
    fi
}

# Count by extension
count_by_ext() {
    local dir="$1"
    local ext="$2"
    if [ -d "$dir" ]; then
        find "$dir" -type f -name "*.$ext" \
            -not -path '*/.git/*' \
            -not -path '*/node_modules/*' \
            -not -path '*/.next/*' \
            -not -path '*/__pycache__/*' \
            -not -path '*/.venv/*' \
            | wc -l | tr -d ' '
    else
        echo "0"
    fi
}

# Count files for each repo
MON_IPAD=$(count_local "$REPO_ROOT")
echo "  mon-ipad: $MON_IPAD files"

# For satellite repos, count via git ls-tree on their remotes
# (since we don't have local checkouts, use git ls-remote + local subtrees)
# If subtree dirs exist locally, count them; otherwise use last known counts

# Check if satellite repos have local working trees (they don't on VM, only via push)
# We'll count from git archive if possible, otherwise from known state

# Mon-ipad breakdown
MON_PY=$(count_by_ext "$REPO_ROOT" "py")
MON_JS=$(count_by_ext "$REPO_ROOT" "js")
MON_TS=$(count_by_ext "$REPO_ROOT" "ts")
MON_TSX=$(count_by_ext "$REPO_ROOT" "tsx")
MON_JSON=$(count_by_ext "$REPO_ROOT" "json")
MON_MD=$(count_by_ext "$REPO_ROOT" "md")
MON_SH=$(count_by_ext "$REPO_ROOT" "sh")
MON_YML=$(count_by_ext "$REPO_ROOT" "yml")
MON_CSS=$(count_by_ext "$REPO_ROOT" "css")

echo "  Breakdown: .py=$MON_PY .ts=$MON_TS .tsx=$MON_TSX .json=$MON_JSON .md=$MON_MD .sh=$MON_SH .yml=$MON_YML .css=$MON_CSS"

# Git object counts for satellite repos (via remote refs)
count_remote_files() {
    local remote="$1"
    local branch="${2:-main}"
    # Try to list all files in the remote's tree
    git ls-tree -r --name-only "$remote/$branch" 2>/dev/null | wc -l | tr -d ' ' || echo "N/A"
}

# Fetch latest refs for satellites (quick, metadata only)
echo ""
echo "  Fetching satellite refs..."
for remote in rag-tests rag-website rag-dashboard rag-data-ingestion; do
    git fetch "$remote" main --depth=1 --quiet 2>/dev/null || echo "  WARN: Could not fetch $remote"
done

RAG_TESTS=$(count_remote_files "rag-tests")
RAG_WEBSITE=$(count_remote_files "rag-website")
RAG_DASHBOARD=$(count_remote_files "rag-dashboard")
RAG_INGESTION=$(count_remote_files "rag-data-ingestion")

echo "  rag-tests: $RAG_TESTS files"
echo "  rag-website: $RAG_WEBSITE files"
echo "  rag-dashboard: $RAG_DASHBOARD files"
echo "  rag-data-ingestion: $RAG_INGESTION files"

TOTAL=$((MON_IPAD + RAG_TESTS + RAG_WEBSITE + RAG_DASHBOARD + RAG_INGESTION))
echo ""
echo "  TOTAL: $TOTAL files across 5 repos"

# Docker containers
DOCKER_COUNT=$(docker ps --format '{{.Names}}' 2>/dev/null | wc -l | tr -d ' ')
DOCKER_LIST=$(docker ps --format '{{.Names}} ({{.Image}}, {{.Status}})' 2>/dev/null || echo "N/A")

# Generate inventory file
cat > "$INVENTORY" << HEREDOC
# Infrastructure Inventory — Automated
> Last updated: $NOW
> Generated by: scripts/inventory-update.sh

## File Counts (precise)

| Repo | Files | Role |
|------|-------|------|
| **mon-ipad** | **$MON_IPAD** | Tour de controle |
| rag-tests | $RAG_TESTS | Tests 4 pipelines |
| rag-website | $RAG_WEBSITE | Site business |
| rag-dashboard | $RAG_DASHBOARD | Dashboard statique |
| rag-data-ingestion | $RAG_INGESTION | Ingestion + enrichissement |
| **TOTAL** | **$TOTAL** | |

## mon-ipad — Breakdown by extension

| Extension | Count |
|-----------|-------|
| .py | $MON_PY |
| .ts | $MON_TS |
| .tsx | $MON_TSX |
| .json | $MON_JSON |
| .md | $MON_MD |
| .sh | $MON_SH |
| .yml | $MON_YML |
| .css | $MON_CSS |

## Docker Containers (VM)

\`\`\`
$DOCKER_LIST
\`\`\`
Total: $DOCKER_COUNT containers

## Cloud Databases

| Service | Index/DB | Quota |
|---------|----------|-------|
| Pinecone sota-rag-jina-1024 | ~10,411 vectors | 100K max (free) |
| Pinecone sota-rag-cohere-1024 | ~10,411 vectors | 100K max (free) |
| Pinecone sota-rag-phase2-graph | ~1,296 vectors | 100K max (free) |
| Neo4j Aura Free | ~19,788 nodes / ~76,717 rels | 200K nodes (free) |
| Supabase | ~40 tables / ~17K rows | 500MB (free) |

## Compute Resources

| Resource | Specs | Role |
|----------|-------|------|
| VM Google Cloud e2-micro | 1 vCPU, 969 MB RAM, 30 GB disk | Pilotage + n8n permanent |
| Codespace rag-tests | 2 cores, 8 GB RAM, 32 GB disk | Tests 50-500q |
| Codespace rag-data-ingestion | 2 cores, 8 GB RAM, 32 GB disk | Ingestion massive |
| Codespace rag-website | 2 cores, 8 GB RAM, 32 GB disk | Dev website |
HEREDOC

echo ""
echo "=== Inventory updated: $INVENTORY ==="
