import { Building2 } from 'lucide-react'
import type { Sector } from '@/types/sector'
import type { AppConnector } from '@/types/connector'

export const PME_SECTOR: Sector = {
  id: 'pme-connectors',
  name: 'Votre Entreprise',
  description: 'Toutes vos applications connectees, une seule conversation intelligente.',
  icon: Building2,
  color: '#0a84ff',
  colorVar: 'var(--ac)',
  gradient: 'from-blue-500/20 to-blue-600/5',
  painPoint: 'Toutes vos apps, une conversation',
  painPointSub: 'Connectez WhatsApp, Gmail, Slack, CRM et 200+ outils — le chatbot agit pour vous.',
  roiPrimary: '12+ apps',
  roiSecondary: '200+ taches',
  roiThird: '2h/jour gagnees',
  metrics: [
    { label: 'Apps connectees', value: '12+' },
    { label: 'Taches automatisees', value: '200+' },
    { label: 'Temps gagne', value: '2h/jour' },
  ],
  useCases: [
    {
      question: 'Envoie un email de relance au client Dupont avec le dernier devis en piece jointe depuis le CRM.',
      label: 'Email + CRM',
      roi: '-30 min/relance',
      description: 'Le chatbot interroge votre CRM, genere l\'email de relance personnalise et l\'envoie via Gmail ou Outlook.',
    },
    {
      question: 'Planifie un RDV de suivi avec le prospect Martin la semaine prochaine et ajoute le brief depuis Salesforce.',
      label: 'CRM + Calendrier',
      roi: '-15 min/RDV',
      description: 'Croisement automatique des disponibilites calendrier avec les infos prospect du CRM.',
    },
    {
      question: 'Resume le canal Slack #projet-alpha des 7 derniers jours et envoie le resume sur Teams.',
      label: 'Slack + Teams',
      roi: '-45 min/semaine',
      description: 'Synthese intelligente des conversations Slack avec distribution automatique sur Teams.',
    },
    {
      question: 'Cree une facture dans Stripe pour le client ABC Consulting basee sur le contrat signe dans Drive.',
      label: 'Drive + Stripe',
      roi: '-20 min/facture',
      description: 'Extraction des montants du contrat et generation automatique de la facture.',
    },
    {
      question: 'Mets a jour la fiche contact HubSpot du client Lemaire avec les notes de l\'appel d\'aujourd\'hui.',
      label: 'HubSpot + Notes',
      roi: '-10 min/appel',
      description: 'Transcription et structuration des notes d\'appel directement dans le CRM.',
    },
  ],
}

export const CONNECTORS: AppConnector[] = [
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    category: 'communication',
    color: '#25D366',
    icon: '💬',
    capabilities: ['Envoi messages', 'Notifications', 'Groupes'],
  },
  {
    id: 'gmail',
    name: 'Gmail',
    category: 'communication',
    color: '#EA4335',
    icon: '📧',
    capabilities: ['Envoi emails', 'Lecture', 'Filtres'],
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'communication',
    color: '#4A154B',
    icon: '💼',
    capabilities: ['Messages', 'Canaux', 'Resumes'],
  },
  {
    id: 'calendar',
    name: 'Google Calendar',
    category: 'productivite',
    color: '#4285F4',
    icon: '📅',
    capabilities: ['Planification', 'Rappels', 'Synchro'],
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    category: 'crm',
    color: '#FF7A59',
    icon: '🎯',
    capabilities: ['Contacts', 'Deals', 'Pipeline'],
  },
  {
    id: 'salesforce',
    name: 'Salesforce',
    category: 'crm',
    color: '#00A1E0',
    icon: '☁️',
    capabilities: ['CRM', 'Reports', 'Leads'],
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'productivite',
    color: '#000000',
    icon: '📝',
    capabilities: ['Docs', 'Bases', 'Wiki'],
  },
  {
    id: 'drive',
    name: 'Google Drive',
    category: 'productivite',
    color: '#0F9D58',
    icon: '📁',
    capabilities: ['Fichiers', 'Partage', 'Recherche'],
  },
  {
    id: 'outlook',
    name: 'Outlook',
    category: 'communication',
    color: '#0078D4',
    icon: '📨',
    capabilities: ['Emails', 'Calendrier', 'Contacts'],
  },
  {
    id: 'teams',
    name: 'Teams',
    category: 'communication',
    color: '#6264A7',
    icon: '👥',
    capabilities: ['Visio', 'Chat', 'Fichiers'],
  },
  {
    id: 'sage',
    name: 'Sage',
    category: 'finance',
    color: '#00DC00',
    icon: '💰',
    capabilities: ['Compta', 'Factures', 'Paie'],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'finance',
    color: '#635BFF',
    icon: '💳',
    capabilities: ['Paiements', 'Factures', 'Abonnements'],
  },
]

export const PME_PAIN_POINTS = [
  { text: 'Vous passez 30 min a copier-coller entre vos apps', color: '#0a84ff' },
  { text: 'Vos emails de relance partent toujours en retard', color: '#30d158' },
  { text: 'Impossible de retrouver cette info dans Slack d\'il y a 3 jours', color: '#bf5af2' },
  { text: 'Votre CRM n\'est jamais a jour apres les appels', color: '#ff9f0a' },
]
